### ISSUE TITLE
Tkinter/Pygame

### ISSUE THREAD

**Issue by jpswales** [jpswales/sharedpython-dev#2]
@ninjavits24 @ryangeorge648 @MSehmi 

We could use Tkinter instead of Pygame, as there are a few issues; Pygame is not compatible with the latest version of Python (our version), so we would have to revert back.
It also seems slightly easier. Programming buttons in Pygame could look like this:
```
def button(msg,x,y,w,h,ic,ac,action=None):
    mouse = pygame.mouse.get_pos()
    click = pygame.mouse.get_pressed()
    print(click)
    if x+w > mouse[0] > x and y+h > mouse[1] > y:
        pygame.draw.rect(gameDisplay, ac,(x,y,w,h))
        if click[0] == 1 and action != None:
            action()         
    else:
        pygame.draw.rect(gameDisplay, ic,(x,y,w,h))
````
In tkinter:
```
btnClick= Button(frame1, text = "Button Text", command = self.new_game)
        btnClick.grid(row = 1, column = 0, sticky = E)
```

_Locked down for collaborators only_

**Comment by ninjavits24** [comment]
I think tkinter will be easier to use personally

**Comment by jpswales** [comment]
Having used it before, I consider it easier also.
Plus, there is no additional software to install, so we can just run it straight away by importing:
`from tkinter import *`

**Comment by ninjavits24** [comment]
I agree. I'm enjoying using pycharm. You should try it out
